version: '3'
services:
  mongo-test:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass

  test:
    build:
      context: src
      dockerfile: Dockerfile.test
    environment:
      - DB_HOST=mongo-test
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - DEBUG=1
      - DB_USERNAME=testuser
      - DB_PASSWORD=testpass
      - REDIS_PASSWORD=testredispass
      - APP_VERSION=21.1.0a1
      - MAILGUN_ENDPOINT=https://api.mailgun.net/v3/mg.example.com/messages
      - FROM_ADDRESS=test@mg.example.com
      - MAILGUN_KEY=fake-mailgun-key
      - FERNET_KEY=QwU0xmHBPLl7lY2aSVgiWE0GiJDn/ReFx/KWDjClgrA=
      - HOST=https://auth.example.com
      - PORTAL_ENABLED=1
    volumes:
      - ./src/app:/app/app
      - ./coverage:/coverage
    depends_on:
      - mongo-test
      - redis-test

  redis-test:
    image: redis:5.0.5-alpine
    command: redis-server --requirepass testredispass

