FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

RUN python3 -m pip install poetry
ADD ./src/pyproject.toml .
ADD ./src/poetry.lock .
RUN poetry export -o requirements.txt
RUN python3 -m pip install -r requirements.txt
COPY ./src/app /app/app
COPY ./src/manage.py /app/manage.py
