FROM python:3.9

RUN pip install pipenv
ADD ./Pipfile .
ADD ./Pipfile.lock .
RUN pipenv install --system --dev

ADD ./app /app/app
COPY ./manage.py /app
WORKDIR /app
CMD pytest --rootdir=/app/app --cov=app