FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

RUN python3 -m pip install poetry
ADD ./pyproject.toml .
ADD ./poetry.lock .
RUN poetry export -o requirements.txt
RUN python3 -m pip install -r requirements.txt
COPY ./app /app/app
