FROM python:3.9

RUN python3 -m pip install poetry
ADD ./pyproject.toml .
ADD ./poetry.lock .
RUN poetry install --no-root

ADD ./app /app/app
COPY ./manage.py /app
WORKDIR /app
ADD ./.coveragerc .
CMD poetry run pytest --rootdir=/app/app --cov-config=./.coveragerc --cov=app --cov-report=xml --cov-report=term && cp coverage.xml /coverage
