FROM python:3.9

RUN pip install pipenv
ADD ./Pipfile .
ADD ./Pipfile.lock .
RUN pipenv install --system --dev

ADD ./app /app/app
COPY ./manage.py /app
WORKDIR /app
ADD ./.coveragerc .
CMD pytest --rootdir=/app/app --cov-config=./.coveragerc --cov=app --cov-report=xml --cov-report=term && cp coverage.xml /coverage